Question 3(d): Computational Analysis For each system in (a), (b) and (c), use python NumPy to define the coefficient matrix A and the augmented matrix M. Compute the determinant of A to test for invertibility and the ranks of A and M to assess consistency via the Rouch´e–Capelli theorem. Use these results to justify your classification from part above. If a unique solution exists, compute it numerically using np.linalg.solve(A, b).

In [1]:
# Question 3 (d): Computational analysis using NumPy (determinant, ranks, classification, solve)  # High-level description

import numpy as nmp  # Import NumPy as 'nmp' per your preference
import pandas as pnd  # Import pandas as 'pnd' per your preference (not used; kept for consistency with your environment)

EPS = 1e-12  # Numerical tolerance to interpret near-zero values as zero (floating-point robustness)

def analyze_system(system_a_in, system_b_in, name="System"):  # Define a helper to analyze one square linear system end-to-end
    A = nmp.array(system_a_in, dtype=float)  # Convert coefficient matrix to a float array for linear algebra operations
    b = nmp.array(system_b_in, dtype=float).reshape(-1, 1)  # Ensure RHS is a column vector of shape (n, 1)

    n_rows, n_cols = A.shape  # Unpack matrix dimensions (rows, cols)
    assert n_rows == n_cols, f"{name}: A must be square; got {n_rows}×{n_cols}"  # Ensure A is square for det/solve
    assert b.shape == (n_rows, 1), f"{name}: b must be shape ({n_rows}, 1); got {b.shape}"  # Ensure b matches A

    M = nmp.concatenate((A, b), axis=1)  # Build augmented matrix M = [A | b] by concatenating along columns

    detA = nmp.linalg.det(A)  # Compute determinant to test invertibility (non-zero => unique solution)
    rankA = nmp.linalg.matrix_rank(A)  # Compute rank of A (dimension of column space)
    rankM = nmp.linalg.matrix_rank(M)  # Compute rank of augmented matrix M = [A | b]

    if abs(detA) > EPS:  # Check if A is invertible using tolerance
        classification = "Unique solution"  # Non-singular matrix implies a unique solution exists
        x = nmp.linalg.solve(A, b.ravel())  # Solve Ax = b numerically (returns 1D array of length n)
    else:  # Singular case: determinant is zero (within tolerance)
        if rankA != rankM:  # Different ranks imply inconsistency by Rouché–Capelli
            classification = "No solution (inconsistent)"  # Inconsistent system classification
            x = None  # No solution vector to return
        else:  # Equal ranks < n imply infinitely many solutions
            classification = "Infinitely many solutions"  # Under-determined but consistent
            x = None  # Not computing a parameterization here; classification is sufficient

    print(f"{name}")  # Header line for readability
    print("A =")  # Label for coefficient matrix
    print(A)  # Display A
    print("b =")  # Label for RHS vector
    print(b.ravel())  # Display b as 1D array for readability
    print("Augmented M = [A | b] =")  # Label for augmented matrix
    print(M)  # Display M
    print(f"det(A) = {detA:.6g}")  # Print determinant in compact format
    print(f"rank(A) = {rankA}, rank(M) = {rankM}")  # Print ranks of A and M
    print(f"Classification: {classification}")  # Print final classification
    if x is not None:  # If a unique solution exists
        print("Unique solution x =")  # Label for solution vector
        print(x)  # Print the solution vector
    print()  # Blank line separation between systems

# Define systems (a), (b), (c)

# System (a):
#   x1 + x2 + x3 = 3
#   x1 − x2 + 2x3 = 2
#   2x1 + 3x3 = 1
A_a = nmp.array([[1,  1, 1],   # Coefficients of eqn 1
                 [1, -1, 2],   # Coefficients of eqn 2
                 [2,  0, 3]],  # Coefficients of eqn 3
                dtype=float)   # Use float dtype
b_a = nmp.array([3, 2, 1], dtype=float)  # Right-hand side values

# System (b):
#   x1 + x2 + x3 = 3
#   x1 − x2 + 2x3 = 2
#   x2 + x3 = 2
A_b = nmp.array([[1,  1, 1],   # Coefficients of eqn 1
                 [1, -1, 2],   # Coefficients of eqn 2
                 [0,  1, 1]],  # Coefficients of eqn 3
                dtype=float)   # Use float dtype
b_b = nmp.array([3, 2, 2], dtype=float)  # Right-hand side values

# System (c):
#   x1 + x2 + x3 = 3
#   x1 − x2 + 2x3 = 2
#   2x1 + 3x3 = 5
A_c = nmp.array([[1,  1, 1],   # Coefficients of eqn 1
                 [1, -1, 2],   # Coefficients of eqn 2
                 [2,  0, 3]],  # Coefficients of eqn 3
                dtype=float)   # Use float dtype
b_c = nmp.array([3, 2, 5], dtype=float)  # Right-hand side values

# Run analyses

analyze_system(A_a, b_a, name="System (a)")  # Analyze and print diagnostics for system (a)
analyze_system(A_b, b_b, name="System (b)")  # Analyze and print diagnostics for system (b)
analyze_system(A_c, b_c, name="System (c)")  # Analyze and print diagnostics for system (c)

System (a)
A =
[[ 1.  1.  1.]
 [ 1. -1.  2.]
 [ 2.  0.  3.]]
b =
[3. 2. 1.]
Augmented M = [A | b] =
[[ 1.  1.  1.  3.]
 [ 1. -1.  2.  2.]
 [ 2.  0.  3.  1.]]
det(A) = 0
rank(A) = 2, rank(M) = 3
Classification: No solution (inconsistent)

System (b)
A =
[[ 1.  1.  1.]
 [ 1. -1.  2.]
 [ 0.  1.  1.]]
b =
[3. 2. 2.]
Augmented M = [A | b] =
[[ 1.  1.  1.  3.]
 [ 1. -1.  2.  2.]
 [ 0.  1.  1.  2.]]
det(A) = -3
rank(A) = 3, rank(M) = 3
Classification: Unique solution
Unique solution x =
[1. 1. 1.]

System (c)
A =
[[ 1.  1.  1.]
 [ 1. -1.  2.]
 [ 2.  0.  3.]]
b =
[3. 2. 5.]
Augmented M = [A | b] =
[[ 1.  1.  1.  3.]
 [ 1. -1.  2.  2.]
 [ 2.  0.  3.  5.]]
det(A) = 0
rank(A) = 2, rank(M) = 2
Classification: Infinitely many solutions



Question 4(d):Using python NumPy library and verify your manual solution. Define the coefficient matrix A and constant vector b for your system. Use np.linalg.solve(A, b) to compute the solution vector. Confirm the accuracy of your manual results by comparing them with this computed solution. Export your Python code as a PDF file with solution and submit

In [4]:
# Question 4(d): Verify admissions linear system with NumPy  # High-level description

import numpy as nmp  # Import NumPy with preferred alias 'nmp'

# Build coefficient matrix A and RHS vector b

A = nmp.array([  # Define the 4×4 coefficient matrix A
    [1, 1, 1, 1],   # Eq (1): total students: x1 + x2 + x3 + x4 = 10
    [1, 2, 3, 4],   # Eq (2): faculty units: 1*x1 + 2*x2 + 3*x3 + 4*x4 = 23
    [2, 1, 2, 1],   # Eq (3): tutoring hours: 2*x1 + 1*x2 + 2*x3 + 1*x4 = 17
    [1, 0, 1, 2]    # Eq (4): lab seats: 1*x1 + 0*x2 + 1*x3 + 2*x4 = 9
], dtype=float)  # Use float for stable linear algebra

b = nmp.array([10, 23, 17, 9], dtype=float)  # Define RHS vector b with the capacities

# Determinant, ranks, classification

detA = nmp.linalg.det(A)  # Compute determinant of A (nonzero => invertible => unique solution)
rankA = nmp.linalg.matrix_rank(A)  # Compute rank of A
M = nmp.concatenate((A, b.reshape(-1, 1)), axis=1)  # Form augmented matrix M = [A | b]
rankM = nmp.linalg.matrix_rank(M)  # Compute rank of augmented matrix

# Solve (since A is expected to be invertible)
    
x = nmp.linalg.solve(A, b)  # Solve A x = b for the solution vector x

# Print results clearly

print("Coefficient matrix A:\n", A)  # Show A
print("\nRHS vector b:\n", b)  # Show b
print("\nAugmented matrix M = [A | b]:\n", M)  # Show augmented matrix

print(f"\nDeterminant det(A) = {detA:.6f}")  # Print determinant
print(f"rank(A) = {rankA}, rank(M) = {rankM}")  # Print ranks

classification = "Unique solution" if abs(detA) > 1e-12 else ("Consistent (infinitely many)" if rankA == rankM else "Inconsistent")  # Classify
print(f"Classification: {classification}")  # Show classification

print("\nSolution vector x (order: [x1, x2, x3, x4]):")  # Label for solution
print(x)  # Print numeric solution

# Sanity check: verify A @ x equals b

print("\nA @ x:\n", A @ x)  # Compute product A x
print("Allclose(A @ x, b)?", nmp.allclose(A @ x, b))  # Check numerical equality within tolerance

Coefficient matrix A:
 [[1. 1. 1. 1.]
 [1. 2. 3. 4.]
 [2. 1. 2. 1.]
 [1. 0. 1. 2.]]

RHS vector b:
 [10. 23. 17.  9.]

Augmented matrix M = [A | b]:
 [[ 1.  1.  1.  1. 10.]
 [ 1.  2.  3.  4. 23.]
 [ 2.  1.  2.  1. 17.]
 [ 1.  0.  1.  2.  9.]]

Determinant det(A) = 4.000000
rank(A) = 4, rank(M) = 4
Classification: Unique solution

Solution vector x (order: [x1, x2, x3, x4]):
[3. 2. 4. 1.]

A @ x:
 [10. 23. 17.  9.]
Allclose(A @ x, b)? True


Question 5(d):
(d) Interpret the solution geometrically as the orthogonal projection of y onto the column space of X. Explain how this projection corresponds to minimizing the squared error in machine learning, and compute the residual vector ∥y − Xw∥2. Finally, verify your result using Python.

In [1]:
# Question 5: Verify Least Squares Solution using Python
# -------------------------------------------------------
# This code performs the following steps:
# 1) Builds X and y from the dataset.
# 2) Computes X^T X and X^T y.
# 3) Solves (X^T X) w = X^T y using manual Gaussian elimination.
# 4) Computes predictions, residuals, and residual norm.

import numpy as nmp  # Use NumPy for array handling

# Step 1: Build X and y

X = nmp.array([
    [1, 1000, 2],
    [1, 1500, 3],
    [1, 1200, 2],
    [1, 2000, 4],
    [1, 1800, 3]
], dtype=float)

y = nmp.array([200000, 300000, 240000, 400000, 350000], dtype=float).reshape(-1, 1)

# Step 2: Compute X^T X and X^T y

XT_X = X.T @ X
XT_y = X.T @ y

print("X^T X:\n", XT_X)
print("\nX^T y:\n", XT_y)
  
# Step 3: Manual Gaussian Elimination

def gaussian_elimination(A, b):
    A = A.astype(float).copy()
    b = b.astype(float).copy()
    n = len(b)

    # Forward elimination
    for i in range(n):
        # Normalize pivot row
        pivot = A[i, i]
        A[i] = A[i] / pivot
        b[i] = b[i] / pivot

        # Eliminate below
        for j in range(i + 1, n):
            factor = A[j, i]
            A[j] -= factor * A[i]
            b[j] -= factor * b[i]

    # Back substitution
    for i in range(n - 1, -1, -1):
        for j in range(i):
            factor = A[j, i]
            A[j] -= factor * A[i]
            b[j] -= factor * b[i]

    return b

w = gaussian_elimination(XT_X, XT_y)
print("\nSolution vector w (bias, size weight, bedrooms weight):\n", w)

# Step 4: Predictions and Residuals

y_pred = X @ w
residual = y - y_pred
residual_norm_sq = float((residual.T @ residual)[0, 0])

print("\nPredicted y:\n", y_pred)
print("\nResiduals:\n", residual)
print("\nSquared residual norm ||y - Xw||^2:", residual_norm_sq)

X^T X:
 [[5.000e+00 7.500e+03 1.400e+01]
 [7.500e+03 1.193e+07 2.230e+04]
 [1.400e+01 2.230e+04 4.200e+01]]

X^T y:
 [[1.490e+06]
 [2.368e+09]
 [4.430e+06]]

Solution vector w (bias, size weight, bedrooms weight):
 [[ 5420.56074766]
 [  172.89719626]
 [11869.1588785 ]]

Predicted y:
 [[202056.07476636]
 [300373.8317757 ]
 [236635.51401869]
 [398691.58878505]
 [352242.99065421]]

Residuals:
 [[-2056.07476636]
 [ -373.8317757 ]
 [ 3364.48598131]
 [ 1308.41121495]
 [-2242.99065421]]

Squared residual norm ||y - Xw||^2: 22429906.542055726
